"use client";

import { FormEvent, useState } from "react";

type EditField = { name: string; label: string; type?: "text" | "number" | "date" | "select" | "textarea"; options?: { value: string; label: string }[] };

export function EditRecordDialog({ title, fields, initialValues, isSubmitting = false, submitError, onClose, onSubmit }: { title: string; fields: EditField[]; initialValues: object; isSubmitting?: boolean; submitError?: string | null; onClose: () => void; onSubmit: (values: Record<string, string>) => void }) {
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(fields.map((field) => [field.name, (initialValues as Record<string, unknown>)[field.name] == null ? "" : String((initialValues as Record<string, unknown>)[field.name])])));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit(values); }
  return <div className="fixed inset-0 z-50 overflow-y-auto overflow-x-hidden bg-slate-950/50 p-0 sm:p-4"><div className="min-h-full w-full min-w-0 bg-white p-5 shadow-xl sm:mx-auto sm:max-w-2xl sm:rounded-2xl sm:p-6"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-xl font-bold">{title}</h2><button className="min-h-11 rounded-xl border border-slate-300 px-4 py-2 font-bold" onClick={onClose} type="button">Cancel</button></div><form className="grid min-w-0 gap-4 overflow-x-hidden" onSubmit={submit} noValidate>{fields.map((field) => <label className="grid min-w-0 gap-1 text-sm font-medium text-slate-700" key={field.name}>{field.label}{field.type === "textarea" ? <textarea className="min-h-24 w-full min-w-0 rounded-md border border-slate-300 px-3 py-2" value={values[field.name] ?? ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} /> : field.type === "select" ? <select className="min-h-11 w-full min-w-0 rounded-md border border-slate-300 px-3 py-2" value={values[field.name] ?? ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })}>{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input className="min-h-11 w-full min-w-0 rounded-md border border-slate-300 px-3 py-2" inputMode={field.type === "number" ? "decimal" : undefined} type={field.type === "date" ? "date" : "text"} value={values[field.name] ?? ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} />}</label>)}{submitError ? <p className="rounded-lg bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700">{submitError}</p> : null}<button className="min-h-11 w-full rounded-md bg-blue-600 px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60" disabled={isSubmitting} type="submit">{isSubmitting ? "Saving…" : "Save changes"}</button></form></div></div>;
}
