import { apiRequest } from "@/services/api";
import { AdCampaign, AdCampaignCreate, AdMetric, AdMetricCreate, AdvertisingSummary, AdvertisingTrendPoint, CampaignPerformance } from "@/types/advertising";

function authHeaders(workspaceId?: string, token?: string) { return { ...(workspaceId ? { "X-Workspace-ID": workspaceId } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function rangeQuery(startDate?: string, endDate?: string, extra?: Record<string, string | number | undefined>) { const params = new URLSearchParams(); if (startDate?.trim()) params.set("start_date", startDate.trim()); if (endDate?.trim()) params.set("end_date", endDate.trim()); Object.entries(extra ?? {}).forEach(([key, value]) => { if (value !== undefined && String(value).trim()) params.set(key, String(value).trim()); }); const query = params.toString(); return query ? `?${query}` : ""; }
export const fetchAdCampaigns = (workspaceId: string, token?: string) => apiRequest<AdCampaign[]>("/advertising/campaigns", { headers: authHeaders(workspaceId, token) });
export const createAdCampaign = (workspaceId: string, token: string | undefined, payload: AdCampaignCreate) => apiRequest<AdCampaign>("/advertising/campaigns", { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify(payload) });
export const updateAdCampaign = (workspaceId: string, campaignId: string, token: string | undefined, payload: Partial<AdCampaignCreate>) => apiRequest<AdCampaign>(`/advertising/campaigns/${campaignId}`, { method: "PUT", headers: authHeaders(workspaceId, token), body: JSON.stringify(payload) });
export const fetchAdMetrics = (workspaceId: string, token?: string) => apiRequest<AdMetric[]>("/advertising/metrics", { headers: authHeaders(workspaceId, token) });
export const createAdMetric = (workspaceId: string, token: string | undefined, payload: AdMetricCreate) => apiRequest<AdMetric>("/advertising/metrics", { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify(payload) });
export const updateAdMetric = (workspaceId: string, metricId: string, token: string | undefined, payload: Partial<Omit<AdMetricCreate, "campaign_id">>) => apiRequest<AdMetric>(`/advertising/metrics/${metricId}`, { method: "PUT", headers: authHeaders(workspaceId, token), body: JSON.stringify(payload) });
export const fetchAdvertisingSummary = (workspaceId: string, token?: string, startDate?: string, endDate?: string) => apiRequest<AdvertisingSummary>(`/advertising/summary${rangeQuery(startDate, endDate)}`, { headers: authHeaders(workspaceId, token) });
export const fetchCampaignPerformance = (workspaceId: string, token?: string, startDate?: string, endDate?: string, limit = 10) => apiRequest<CampaignPerformance[]>(`/advertising/campaign-performance${rangeQuery(startDate, endDate, { limit })}`, { headers: authHeaders(workspaceId, token) });
export const fetchAdvertisingTrend = (workspaceId: string, token?: string, startDate?: string, endDate?: string) => apiRequest<AdvertisingTrendPoint[]>(`/advertising/trend${rangeQuery(startDate, endDate)}`, { headers: authHeaders(workspaceId, token) });

export const deleteAdCampaign = (workspaceId: string, campaignId: string, token?: string) => apiRequest<void>(`/advertising/campaigns/${campaignId}`, { method: "DELETE", headers: authHeaders(workspaceId, token) });
export const deleteAdMetric = (workspaceId: string, metricId: string, token?: string) => apiRequest<void>(`/advertising/metrics/${metricId}`, { method: "DELETE", headers: authHeaders(workspaceId, token) });
