import { apiRequest, authenticatedFetch } from "@/services/api";
import { ImportJob, ImportLog, ImportPreview, ImportReport, MappingPreset, MappingSuggestion, ValidationReport } from "@/types/import-center";

function authHeaders(workspaceId?: string, token?: string) { return { ...(workspaceId ? { "X-Workspace-ID": workspaceId } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
export async function uploadImportFile(workspaceId: string | undefined, file: File, token?: string) { const form = new FormData(); form.append("file", file); const response = await authenticatedFetch("/import/upload", { method: "POST", body: form, headers: authHeaders(workspaceId, token) }); if (!response.ok) throw new Error(`Sellora API request failed: ${response.status}`); return response.json() as Promise<{ job_id: string; status: string; file_name: string }>; }
export const fetchImportSheets = (workspaceId: string | undefined, jobId: string, token?: string) => apiRequest<{ sheets: string[] }>(`/import/${jobId}/sheets`, { headers: authHeaders(workspaceId, token) });
export const previewImportSheet = (workspaceId: string | undefined, jobId: string, sheetName: string, limit: number, token?: string) => apiRequest<ImportPreview>(`/import/${jobId}/preview`, { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify({ sheet_name: sheetName, limit }) });
export const validateImportMapping = (workspaceId: string | undefined, jobId: string, entityType: string, sheetName: string, columnMapping: Record<string, string>, token?: string) => apiRequest<ValidationReport>(`/import/${jobId}/validate`, { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify({ entity_type: entityType, sheet_name: sheetName, column_mapping: columnMapping }) });
export const executeImport = (workspaceId: string | undefined, jobId: string, entityType: string, sheetName: string, columnMapping: Record<string, string>, token?: string) => apiRequest<{ job: ImportJob }>(`/import/${jobId}/execute`, { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify({ entity_type: entityType, sheet_name: sheetName, column_mapping: columnMapping, mode: "create_only" }) });
export const fetchImportLogs = (workspaceId: string | undefined, jobId: string, token?: string) => apiRequest<ImportLog[]>(`/import/${jobId}/logs`, { headers: authHeaders(workspaceId, token) });
export const fetchYourJewelryPreset = (workspaceId?: string, token?: string) => apiRequest<MappingPreset>("/import/presets/your_jewelry_excel_v1", { headers: authHeaders(workspaceId, token) });
export const fetchProductCatalogPreset = (workspaceId?: string, token?: string) => apiRequest<MappingPreset>("/import/presets/your_jewelry_product_catalog_v1", { headers: authHeaders(workspaceId, token) });
export const suggestImportMapping = (workspaceId: string | undefined, jobId: string, sheetName: string, entityType: string, token?: string) => apiRequest<MappingSuggestion>(`/import/${jobId}/suggest-mapping`, { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify({ sheet_name: sheetName, entity_type: entityType }) });
export const dryRunImport = (workspaceId: string | undefined, jobId: string, entityType: string, sheetName: string, columnMapping: Record<string, string>, token?: string) => apiRequest<ImportReport>(`/import/${jobId}/dry-run`, { method: "POST", headers: authHeaders(workspaceId, token), body: JSON.stringify({ entity_type: entityType, sheet_name: sheetName, column_mapping: columnMapping }) });
