export type ImportJobStatus = "UPLOADED" | "PREVIEWED" | "VALIDATED" | "IMPORTING" | "COMPLETED" | "FAILED" | "PARTIALLY_COMPLETED" | "CANCELLED";
export type ImportJob = { id: string; workspace_id: string; file_name: string; file_type: string; status: ImportJobStatus; total_rows: number; processed_rows: number; success_rows: number; failed_rows: number; created_at: string; updated_at: string; completed_at?: string | null };
export type ImportLog = { id: string; row_number?: number | null; entity_type: string; status: "SUCCESS" | "FAILED" | "SKIPPED" | "WARNING"; message?: string | null; raw_data?: Record<string, unknown> | null; created_at: string };
export type ImportPreview = { columns: string[]; rows: Record<string, unknown>[] };
export type ValidationIssue = { row_number?: number | null; severity: "ERROR" | "WARNING"; field?: string | null; message: string; raw_value?: unknown; normalized_value?: unknown };
export type ValidationReport = { is_valid: boolean; total_rows: number; errors: string[]; warnings: string[]; issues: ValidationIssue[] };
export type ImportReport = { job_id: string; entity_type: string; sheet_name: string; total_rows: number; valid_rows: number; warning_rows: number; error_rows: number; skipped_rows: number; duplicate_rows: number; ready_to_import_rows: number; estimated_entities_to_create: number; sample_errors: ValidationIssue[]; sample_warnings: ValidationIssue[] };
export type MappingPreset = { name: string; sheets: string[]; mappings: Record<string, Record<string, string>> };
export type MappingSuggestion = { suggested_mapping: Record<string, string>; confidence: Record<string, number>; unmapped_columns: string[]; required_fields_missing: string[] };
