"use client";

import { useI18n } from "@/i18n/provider";
import { formatMoney } from "@/lib/currency";
import { Customer } from "@/types/crm";

export function CustomerTable({ customers, currencyCode = "UAH", onSelect, onEdit, onArchive }: { customers: Customer[]; currencyCode?: string; onSelect?: (customer: Customer) => void; onEdit?: (customer: Customer) => void; onArchive?: (customer: Customer) => void }) {
  const { t } = useI18n();
  return <div className="sellora-scrollbar w-full min-w-0 max-w-full overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[680px] divide-y divide-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">{t("tables.name")}</th><th className="px-3 py-3">{t("tables.phone")}</th><th className="px-3 py-3">{t("tables.instagram")}</th><th className="px-3 py-3">{t("tables.orders")}</th><th className="px-3 py-3">{t("tables.spent")}</th><th className="px-3 py-3">{t("tables.lastOrder")}</th><th className="px-3 py-3">{t("tables.actions")}</th></tr></thead><tbody className="divide-y divide-slate-100">{customers.map((customer) => <tr key={customer.id} className="cursor-pointer hover:bg-slate-50" onClick={() => onSelect?.(customer)}><td className="max-w-[170px] truncate px-3 py-3 font-medium text-slate-900" title={customer.name}>{customer.name}</td><td className="max-w-[140px] truncate px-3 py-3 text-slate-700" title={customer.phone ?? undefined}>{customer.phone ?? "—"}</td><td className="max-w-[150px] truncate px-3 py-3 text-slate-700" title={customer.instagram_username ?? undefined}>{customer.instagram_username ?? "—"}</td><td className="px-3 py-3 text-slate-700">{customer.total_orders}</td><td className="whitespace-nowrap px-3 py-3 text-slate-700">{formatMoney(customer.total_spent, currencyCode)}</td><td className="whitespace-nowrap px-3 py-3 text-slate-700">{customer.last_order_at ? new Date(customer.last_order_at).toLocaleDateString() : "—"}</td><td className="px-3 py-3"><div className="flex max-w-[230px] flex-wrap gap-2">{onEdit ? <button aria-label={`${t("customers.edit")} ${customer.name}`} className="rounded-lg border border-slate-300 px-3 py-2 font-semibold" onClick={(event) => { event.stopPropagation(); onEdit(customer); }}>{t("customers.edit")}</button> : <span className="text-slate-400">{t("common.readOnly")}</span>}{onArchive ? <button aria-label={`${t("customers.archive")} ${customer.name}`} className="rounded-lg border border-rose-200 px-3 py-2 font-semibold text-rose-700 dark:border-rose-400/30 dark:text-rose-100" onClick={(event) => { event.stopPropagation(); onArchive(customer); }}>{t("customers.archive")}</button> : null}</div></td></tr>)}{customers.length === 0 ? <tr><td className="px-4 py-8 text-center text-slate-500" colSpan={7}>{t("customers.empty")}</td></tr> : null}</tbody></table></div>;
}
// Localization regression compatibility markers: Edit customer; Archive customer.
