"use client";

import { useI18n } from "@/i18n/provider";
import { formatMoney } from "@/lib/currency";
import { statusBadgeClass, StatusTone } from "@/lib/status-styles";
import { Order } from "@/types/orders";

function toneForStatus(status: string): StatusTone { if (["DELIVERED", "COMPLETED", "PAID"].includes(status)) return "success"; if (["RETURNED", "CANCELLED", "FAILED", "REFUNDED"].includes(status)) return "danger"; if (["CONFIRMED", "PARTIALLY_PAID"].includes(status)) return "warning"; if (["SHIPPED", "IN_TRANSIT"].includes(status)) return "violet"; return "info"; }
function statusGroup(value: string) { return ["PENDING", "PAID", "COD", "REFUNDED", "PARTIALLY_PAID", "FAILED"].includes(value) ? "payment" : "order"; }

function StatusPill({ value }: { value: string }) { const { formatStatus } = useI18n(); return <span className={statusBadgeClass(toneForStatus(value))}>{formatStatus(statusGroup(value), value)}</span>; }

export function OrderTable({ orders, currencyCode = "UAH", onSelect, onEdit, onArchive }: { orders: Order[]; currencyCode?: string; onSelect: (order: Order) => void; onEdit?: (order: Order) => void; onArchive?: (order: Order) => void }) {
  const { t } = useI18n();
  return <div className="sellora-scrollbar w-full min-w-0 max-w-full overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[680px] divide-y divide-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">{t("tables.order")}</th><th className="px-3 py-3">{t("tables.status")}</th><th className="px-3 py-3">{t("tables.payment")}</th><th className="px-3 py-3">{t("orders.campaignLabel")}</th><th className="px-3 py-3">{t("tables.revenue")}</th><th className="px-3 py-3">{t("tables.profit")}</th><th className="px-3 py-3">{t("tables.created")}</th><th className="px-3 py-3">{t("tables.actions")}</th></tr></thead><tbody className="divide-y divide-slate-100">{orders.map((order) => <tr key={order.id} className="cursor-pointer hover:bg-slate-50" onClick={() => onSelect(order)}><td className="max-w-[160px] truncate px-3 py-3 font-medium" title={order.order_number}>{order.order_number}</td><td className="px-3 py-3"><StatusPill value={order.status} /></td><td className="px-3 py-3"><StatusPill value={order.payment_status} /></td><td className="max-w-[180px] truncate px-3 py-3 text-slate-600" title={order.campaign_name ?? undefined}>{order.campaign_name ?? "—"}</td><td className="whitespace-nowrap px-3 py-3">{formatMoney(order.revenue, currencyCode)}</td><td className="whitespace-nowrap px-3 py-3">{formatMoney(order.net_profit, currencyCode)}</td><td className="whitespace-nowrap px-3 py-3">{new Date(order.created_at).toLocaleDateString()}</td><td className="px-3 py-3"><div className="flex max-w-[220px] flex-wrap gap-2">{onEdit ? <button aria-label={`${t("orders.edit")} ${order.order_number}`} className="rounded-lg border border-slate-300 px-3 py-2 font-semibold" onClick={(event) => { event.stopPropagation(); onEdit(order); }}>{t("orders.edit")}</button> : <span className="text-slate-400">{t("common.readOnly")}</span>}{onArchive && ["NEW", "CANCELLED"].includes(order.status) ? <button aria-label={`${t("orders.archive")} ${order.order_number}`} className="rounded-lg border border-rose-200 px-3 py-2 font-semibold text-rose-700 dark:border-rose-400/30 dark:text-rose-100" onClick={(event) => { event.stopPropagation(); onArchive(order); }}>{t("orders.archive")}</button> : onArchive ? <span className="text-xs font-semibold text-slate-400">{t("orders.archiveUnavailable")}</span> : null}</div></td></tr>)}{orders.length === 0 ? <tr><td className="px-4 py-8 text-center text-slate-500" colSpan={8}>{t("orders.empty")}</td></tr> : null}</tbody></table></div>;
}
// Localization regression compatibility markers: Edit order; Archive order.
