"""add ai direct intelligence foundation

Revision ID: 202607180027
Revises: 202607180026
Create Date: 2026-07-18 09:00:00.000000
"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "202607180027"
down_revision: str | None = "202607180026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def ts(name='created_at'):
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False)

def uuid_col(name, nullable=False):
    return sa.Column(name, postgresql.UUID(as_uuid=True), nullable=nullable)

def upgrade() -> None:
    op.create_table('direct_conversations', uuid_col('id'), uuid_col('workspace_id'), sa.Column('channel', sa.String(30), nullable=False), sa.Column('external_account_id', sa.String(160)), sa.Column('external_conversation_id', sa.String(160)), sa.Column('participant_external_id', sa.String(160)), sa.Column('participant_username', sa.String(160)), sa.Column('participant_display_name', sa.String(255)), uuid_col('linked_lead_id', True), uuid_col('linked_customer_id', True), uuid_col('linked_order_id', True), sa.Column('status', sa.String(40), server_default='OPEN', nullable=False), sa.Column('priority', sa.String(20), server_default='NORMAL', nullable=False), uuid_col('assigned_user_id', True), sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False), sa.Column('last_message_at', sa.DateTime(timezone=True)), sa.Column('last_inbound_message_at', sa.DateTime(timezone=True)), sa.Column('last_outbound_message_at', sa.DateTime(timezone=True)), sa.Column('ai_processing_status', sa.String(40), server_default='NOT_REQUESTED', nullable=False), uuid_col('latest_ai_analysis_id', True), ts(), ts('updated_at'), sa.Column('deleted_at', sa.DateTime(timezone=True)), uuid_col('deleted_by', True), uuid_col('created_by', True), uuid_col('updated_by', True), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['linked_lead_id'], ['leads.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['linked_customer_id'], ['customers.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['linked_order_id'], ['orders.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'))
    op.create_table('direct_messages', uuid_col('id'), uuid_col('workspace_id'), uuid_col('conversation_id'), sa.Column('external_message_id', sa.String(160)), sa.Column('direction', sa.String(20), nullable=False), sa.Column('sender_type', sa.String(20), nullable=False), sa.Column('message_type', sa.String(30), server_default='TEXT', nullable=False), sa.Column('text', sa.Text()), sa.Column('safe_text_hash', sa.String(64)), sa.Column('received_at', sa.DateTime(timezone=True), nullable=False), sa.Column('sent_at', sa.DateTime(timezone=True)), sa.Column('processing_status', sa.String(30), server_default='RECEIVED', nullable=False), sa.Column('is_synthetic', sa.Boolean(), server_default=sa.false(), nullable=False), ts(), ts('updated_at'), sa.Column('deleted_at', sa.DateTime(timezone=True)), uuid_col('deleted_by', True), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'))
    op.create_table('ai_workspace_settings', uuid_col('id'), uuid_col('workspace_id'), sa.Column('enabled', sa.Boolean(), server_default=sa.false(), nullable=False), sa.Column('synthetic_inbox_enabled', sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column('direct_intelligence_enabled', sa.Boolean(), server_default=sa.false(), nullable=False), sa.Column('auto_analysis_enabled', sa.Boolean(), server_default=sa.false(), nullable=False), sa.Column('reply_suggestions_enabled', sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column('action_drafts_enabled', sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column('daily_request_limit', sa.Integer(), server_default='100', nullable=False), sa.Column('daily_token_limit', sa.Integer(), server_default='100000', nullable=False), sa.Column('monthly_budget_usd', sa.Numeric(12,2), server_default='25', nullable=False), sa.Column('max_context_messages', sa.Integer(), server_default='20', nullable=False), sa.Column('max_input_characters', sa.Integer(), server_default='12000', nullable=False), sa.Column('minimum_action_confidence', sa.Numeric(5,4), server_default='0.85', nullable=False), sa.Column('minimum_product_match_confidence', sa.Numeric(5,4), server_default='0.85', nullable=False), ts(), ts('updated_at'), uuid_col('updated_by', True), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('workspace_id', name='uq_ai_workspace_settings_workspace_id'))
    op.create_table('ai_analyses', uuid_col('id'), uuid_col('workspace_id'), uuid_col('conversation_id'), uuid_col('source_message_id'), sa.Column('provider', sa.String(40), nullable=False), sa.Column('model', sa.String(120), nullable=False), sa.Column('prompt_key', sa.String(80), nullable=False), sa.Column('prompt_version', sa.String(40), nullable=False), sa.Column('status', sa.String(40), nullable=False), sa.Column('detected_language', sa.String(12)), sa.Column('detected_intent', sa.String(60)), sa.Column('intent_confidence', sa.Numeric(5,4)), sa.Column('sentiment', sa.String(20)), sa.Column('sentiment_confidence', sa.Numeric(5,4)), sa.Column('urgency', sa.String(20)), sa.Column('requires_human', sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column('clarification_required', sa.Boolean(), server_default=sa.false(), nullable=False), sa.Column('structured_result', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False), sa.Column('safe_error_code', sa.String(120)), sa.Column('safe_error_message', sa.Text()), sa.Column('provider_request_id', sa.String(160)), sa.Column('input_tokens', sa.Integer()), sa.Column('output_tokens', sa.Integer()), sa.Column('total_tokens', sa.Integer()), sa.Column('estimated_cost_usd', sa.Numeric(12,6)), sa.Column('latency_ms', sa.Integer()), sa.Column('started_at', sa.DateTime(timezone=True)), sa.Column('completed_at', sa.DateTime(timezone=True)), ts(), uuid_col('created_by', True), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['source_message_id'], ['direct_messages.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'))
    op.create_table('ai_suggestions', uuid_col('id'), uuid_col('workspace_id'), uuid_col('conversation_id'), uuid_col('analysis_id'), sa.Column('suggestion_type', sa.String(60), nullable=False), sa.Column('status', sa.String(40), server_default='REVIEW_REQUIRED', nullable=False), sa.Column('title', sa.String(255), nullable=False), sa.Column('summary', sa.Text()), sa.Column('draft_text', sa.Text()), sa.Column('structured_payload', postgresql.JSONB()), sa.Column('confidence', sa.Numeric(5,4)), uuid_col('reviewed_by', True), sa.Column('reviewed_at', sa.DateTime(timezone=True)), sa.Column('rejection_reason', sa.String(500)), sa.Column('applied_entity_type', sa.String(80)), uuid_col('applied_entity_id', True), ts(), ts('updated_at'), sa.Column('expires_at', sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'))
    op.create_table('ai_action_drafts', uuid_col('id'), uuid_col('workspace_id'), uuid_col('conversation_id'), uuid_col('suggestion_id'), sa.Column('action_type', sa.String(60), nullable=False), sa.Column('status', sa.String(40), server_default='DRAFT', nullable=False), sa.Column('payload', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False), sa.Column('validation_errors', postgresql.JSONB()), sa.Column('validation_warnings', postgresql.JSONB()), uuid_col('approved_by', True), sa.Column('approved_at', sa.DateTime(timezone=True)), sa.Column('applied_at', sa.DateTime(timezone=True)), sa.Column('result_entity_type', sa.String(80)), uuid_col('result_entity_id', True), sa.Column('idempotency_key', sa.String(160), nullable=False), sa.Column('request_fingerprint', sa.String(64), nullable=False), ts(), ts('updated_at'), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['suggestion_id'], ['ai_suggestions.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('workspace_id','idempotency_key', name='uq_ai_action_drafts_workspace_idempotency_key'))
    op.create_table('ai_usage_events', uuid_col('id'), uuid_col('workspace_id'), uuid_col('user_id', True), uuid_col('conversation_id', True), uuid_col('analysis_id', True), sa.Column('provider', sa.String(40), nullable=False), sa.Column('model', sa.String(120), nullable=False), sa.Column('request_type', sa.String(80), nullable=False), sa.Column('status', sa.String(40), nullable=False), sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False), sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False), sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False), sa.Column('estimated_cost_usd', sa.Numeric(12,6), server_default='0', nullable=False), sa.Column('latency_ms', sa.Integer()), ts(), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'))
    op.create_table('ai_feedback', uuid_col('id'), uuid_col('workspace_id'), uuid_col('analysis_id', True), uuid_col('suggestion_id', True), uuid_col('user_id'), sa.Column('rating', sa.String(40), nullable=False), sa.Column('reason', sa.String(500)), sa.Column('corrected_intent', sa.String(60)), sa.Column('corrected_payload', postgresql.JSONB()), ts(), sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['suggestion_id'], ['ai_suggestions.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    for table in ['direct_conversations','direct_messages','ai_analyses','ai_suggestions','ai_action_drafts','ai_usage_events','ai_feedback']:
        op.create_index(f'ix_{table}_workspace_created_at', table, ['workspace_id','created_at'])
    op.create_index('ix_direct_conversations_workspace_status', 'direct_conversations', ['workspace_id','status'])
    op.create_index('ix_direct_messages_workspace_conversation', 'direct_messages', ['workspace_id','conversation_id'])
    op.create_index('ix_ai_usage_events_workspace_request_type', 'ai_usage_events', ['workspace_id','request_type'])
    op.create_index('ix_ai_usage_events_workspace_status', 'ai_usage_events', ['workspace_id','status'])
    op.create_index('ix_ai_usage_events_workspace_model', 'ai_usage_events', ['workspace_id','model'])
    for table in ['direct_conversations','direct_messages','ai_workspace_settings','ai_analyses','ai_suggestions','ai_action_drafts','ai_usage_events','ai_feedback']:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')

def downgrade() -> None:
    for table in ['ai_feedback','ai_usage_events','ai_action_drafts','ai_suggestions','ai_analyses','ai_workspace_settings','direct_messages','direct_conversations']:
        op.drop_table(table)
