"use client";
import { useQuery } from "@tanstack/react-query";
import { safeApiErrorMessage } from "@/services/api";
import { searchNovaPoshtaWarehouses } from "@/services/integrations";
import { NovaPoshtaDirectoryItem } from "@/types/integrations";

export function WarehouseSearchSelect({ workspaceId, cityRef, query, onQuery, onSelect, label = "Nova Poshta warehouse", helperText }: { workspaceId: string; cityRef: string; query: string; onQuery: (value: string) => void; onSelect: (item: NovaPoshtaDirectoryItem) => void; label?: string; helperText?: string }) {
  const warehouses = useQuery({ queryKey: ["np-warehouses", workspaceId, cityRef, query], queryFn: () => searchNovaPoshtaWarehouses(workspaceId, cityRef, query || undefined), enabled: Boolean(cityRef) });
  return <label className="grid gap-2 text-sm font-semibold text-slate-700"><span>{label}</span><input className="min-h-11 rounded-lg border border-slate-300 px-3 disabled:bg-slate-100" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search Nova Poshta warehouse" disabled={!cityRef} />{helperText ? <span className="text-xs font-normal text-slate-500">{helperText}</span> : null}{!cityRef ? <span className="text-xs font-normal text-slate-500">Select or enter a sender city ref before loading warehouses.</span> : null}{warehouses.isError ? <span className="rounded-lg bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700">{safeApiErrorMessage(warehouses.error, "Unable to load warehouses for the selected city.")}</span> : null}{warehouses.isFetching ? <span className="text-xs font-normal text-slate-500">Loading warehouses…</span> : null}{warehouses.data?.length ? <div className="grid max-h-44 gap-1 overflow-y-auto rounded-lg border border-slate-200 bg-white p-2">{warehouses.data.map((warehouse) => <button className="rounded-md px-2 py-2 text-left text-sm hover:bg-slate-50" key={warehouse.ref} type="button" onClick={() => onSelect(warehouse)}>{warehouse.description}</button>)}</div> : null}</label>;
}
